### ISSUE TITLE
Yarn run build, Yarn run start is not working due to css import problems in webpack.

### ISSUE THREAD

**Issue by vydyas** [abolkog/js-playground#22]
I followed this doc and fixed the issue
https://blog.jakoblind.no/css-modules-webpack/

<img width="1680" alt="Screenshot 2022-09-06 at 6 19 17 PM" src="https://user-images.githubusercontent.com/2999586/188639436-7b644b48-4da3-48c2-a7a3-cc95bc847bdb.png">

#Fixthis 

Note: Great code

**Comment by abolkog** [comment]
Thanks @vydyas , I believe this should be fixed now. Feel free to open a PR with your fix if needed
